"""Command-line entry point for rendering a Frame One screen."""

from __future__ import annotations

import argparse
from datetime import datetime
import hashlib
import json
from pathlib import Path
import time

from .displays import display_image
from .providers.claude import claude_provider_state
from .providers.claude_oauth import ClaudeUsageProvider
from .providers.codex import CodexRateLimitProvider
from .providers.gmail import GmailUnreadProvider
from .providers.quotes import quote_provider_state
from .providers.weather import OpenMeteoWeatherProvider, WeatherLocation
from .refresh import (
    APP_SERVER,
    CLAUDE_OAUTH_STALE_SECONDS,
    LOCAL_FILE,
    NETWORK,
    StateCache,
    fetch_with_retry,
    is_due,
    resolve,
)
from .renderer import render_dashboard


DEFAULT_REFRESH_DEADLINE_SECONDS = 120


def main() -> None:
    parser = argparse.ArgumentParser(description="Render a Frame One e-paper PNG.")
    parser.add_argument("--input", type=Path, required=True, help="Dashboard state JSON")
    parser.add_argument("--output", type=Path, required=True, help="Output PNG path")
    parser.add_argument(
        "--display",
        choices=("waveshare-7in5-v2",),
        help="Optionally send the rendered image to a supported physical display",
    )
    parser.add_argument(
        "--live-quote",
        action="store_true",
        help="Fetch and render the live Quote of the Day without storing it separately",
    )
    parser.add_argument("--live-weather", action="store_true", help="Fetch current weather from Open-Meteo")
    parser.add_argument(
        "--claude-status-file",
        type=Path,
        help="Automatic snapshot generated by the Claude Code status-line collector",
    )
    parser.add_argument(
        "--claude-oauth-credentials",
        type=Path,
        help="Read Claude allowance directly using this device's OAuth credential (standalone)",
    )
    parser.add_argument("--live-codex", action="store_true", help="Read allowance from the local Codex App Server")
    parser.add_argument("--gmail-token", type=Path, help="Read Gmail INBOX count using this local OAuth token")
    parser.add_argument("--weather-latitude", type=float, help="Explicit weather location latitude")
    parser.add_argument("--weather-longitude", type=float, help="Explicit weather location longitude")
    parser.add_argument(
        "--weather-timezone",
        default="America/New_York",
        help="IANA timezone used for the forecast (default: America/New_York)",
    )
    parser.add_argument(
        "--refresh-deadline-seconds",
        type=float,
        default=DEFAULT_REFRESH_DEADLINE_SECONDS,
        help="Wall-clock budget shared by every live provider in this round (default: 120)",
    )
    parser.add_argument(
        "--state-cache",
        type=Path,
        help="Last-known-good provider values (default: .frame-one-state.json beside the output)",
    )
    parser.add_argument(
        "--respect-schedule",
        action="store_true",
        help="Skip this run if the overnight hourly cadence says it is not due yet",
    )
    parser.add_argument(
        "--force-display",
        action="store_true",
        help="Send the image to the panel even when nothing visible changed",
    )
    args = parser.parse_args()

    marker = args.output.with_name(f".{args.output.name}.last-render")
    now = datetime.now().astimezone()
    if args.respect_schedule and not is_due(now, _last_render(marker)):
        print("Skipped: overnight cadence, not due yet")
        return

    with args.input.open("r", encoding="utf-8") as state_file:
        state = json.load(state_file)

    deadline = time.monotonic() + max(1.0, args.refresh_deadline_seconds)
    cache = StateCache(args.state_cache or args.output.with_name(".frame-one-state.json"))
    live_sources = False

    # No provider aborts the round: each tile falls back to its last-known-good
    # value and then to an em dash, so one failing source cannot freeze the panel.
    if args.live_weather:
        live_sources = True
        if args.weather_latitude is None or args.weather_longitude is None:
            parser.error("--live-weather requires --weather-latitude and --weather-longitude")
        provider = OpenMeteoWeatherProvider(
            WeatherLocation(args.weather_latitude, args.weather_longitude, args.weather_timezone)
        )
        state["weather"] = _report(
            "weather", resolve("weather", provider.get, cache=cache, now=now, policy=NETWORK, deadline=deadline)
        )

    if args.claude_oauth_credentials and args.claude_status_file:
        parser.error("use either --claude-oauth-credentials or --claude-status-file, not both")

    if args.claude_oauth_credentials:
        live_sources = True
        state["claude"] = _report(
            "claude",
            resolve(
                "claude",
                ClaudeUsageProvider(args.claude_oauth_credentials).get,
                cache=cache,
                now=now,
                policy=NETWORK,
                deadline=deadline,
                stale_after_seconds=CLAUDE_OAUTH_STALE_SECONDS,
            ),
        )
    elif args.claude_status_file:
        live_sources = True
        state["claude"] = _report(
            "claude",
            resolve(
                "claude",
                lambda: claude_provider_state(args.claude_status_file),
                cache=cache,
                now=now,
                policy=LOCAL_FILE,
                deadline=deadline,
            ),
        )

    if args.live_codex:
        live_sources = True
        state["codex"] = _report(
            "codex",
            resolve("codex", CodexRateLimitProvider().get, cache=cache, now=now, policy=APP_SERVER, deadline=deadline),
        )

    if args.gmail_token:
        live_sources = True
        state["gmail"] = _report(
            "gmail",
            resolve(
                "gmail", GmailUnreadProvider(args.gmail_token).get, cache=cache, now=now, policy=NETWORK, deadline=deadline
            ),
        )

    # The quote is deliberately excluded from the cache: DATA_SOURCES.md keeps it
    # live-only, with no stored or substituted quote.  It simply goes quiet.
    if args.live_quote:
        live_sources = True
        state["quote"] = _report(
            "quote", fetch_with_retry(quote_provider_state, policy=NETWORK, deadline=deadline)
        )

    cache.save()

    if live_sources:
        # The header stamp reports when the panel was refreshed, which stays
        # true even when an individual tile came back unavailable.
        state["generated_at"] = now.isoformat()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    image = render_dashboard(state)
    image.save(args.output)
    _record_render(marker, now)
    print(f"Rendered {args.output}")
    if args.display == "waveshare-7in5-v2":
        if _display_if_changed(image, args.output, force=args.force_display):
            print("Updated Waveshare 7.5-inch V2 display")
        else:
            print("Panel left alone: nothing visible changed")


def _report(name: str, state: dict[str, object]) -> dict[str, object]:
    status = state.get("state")
    if status == "stale":
        print(f"{name}: refresh failed; showing last known value")
    elif status == "needs_setup":
        print(f"{name}: not authorized yet; run frame-one-claude-login")
    elif status != "ok":
        print(f"{name}: unavailable after retries; showing em dash")
    return state


def _last_render(marker: Path) -> datetime | None:
    try:
        return datetime.fromisoformat(marker.read_text(encoding="utf-8").strip())
    except (OSError, ValueError):
        return None


def _record_render(marker: Path, moment: datetime) -> None:
    try:
        marker.write_text(moment.isoformat() + "\n", encoding="utf-8")
    except OSError:
        pass


def _display_if_changed(image, output: Path, *, force: bool) -> bool:
    """Write to the panel only when the rendered pixels actually differ.

    A full e-paper refresh is slow and visibly flashes, so at a five-minute
    cadence an unchanged screen should be left alone.
    """
    digest = hashlib.sha256(image.tobytes()).hexdigest()
    marker = output.with_name(f".{output.name}.displayed")
    if not force:
        try:
            if marker.read_text(encoding="utf-8").strip() == digest:
                return False
        except OSError:
            pass
    display_image(image)
    try:
        marker.write_text(digest + "\n", encoding="utf-8")
    except OSError:
        pass
    return True


if __name__ == "__main__":
    main()
